blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#For GraphQL
from django.views.decorators.csrf import csrf_exempt
from .views import PrivateGraphQLView   
# from graphql_jwt.decorators import jwt_cookie

urlpatterns = [
    path('admin/', admin.site.urls),
    #for namespace
    path('core/', include('core.urls', namespace='core')),
    path('users/', include('users.urls', namespace='users')),

    #for GraphQL
    path("graphql", csrf_exempt(PrivateGraphQLView.as_view(graphiql=True))),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from . import views
from django.contrib.auth import views as auth_views
#for post's generic views
from .views import PostCreateView, PostUpdateView, PostDeleteView, PostView


app_name = 'core'

urlpatterns = [
    path('home/', views.HomeView, name='home'),
    
    #For Post Operations

    path('post/<pk>/<slug:slug>', PostView.as_view(), name='post'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post_delete'),

    #for comment
    path('comment/<int:comment_id>/', views.CommentUpdateView, name='comment_update'),
    path('comment_delete/<int:comment_id>/', views.CommentDeleteView, name='comment_delete'),
]

blog/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views

from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView,
)
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.log_in, name='log_in'),
    path('logout/', views.log_out, name='log_out'),
    path('profile/<username>/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    #password_change

    path('password_change/', PasswordChangeView.as_view(
        template_name='users/password_change.html',
        success_url=reverse_lazy('users:password_change_done')),
        name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(
        template_name='users/password_change_done.html'),
        name='password_change_done'),
]

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <title>{% block head_title %}Welcome - Blog{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
      <a href="{% url 'core:home' %}" class="navbar-brand">Django blog</a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
        <div class="navbar-nav">
          <a href="{% url 'core:home' %}"
            class="nav-item nav-link  {% if request.path == '/' %}active{% endif %}">Home</a>
        </div>

        {% if request.user.is_authenticated %}
        <div class="navbar-nav ml-auto">
          <a href="{% url 'core:post_create' %}"
    class="nav-item nav-link {% if request.path == '/post/create/' %}active{% endif %}">
    Create a post
  </a>
          <a href="{% url 'users:profile' request.user.username %}"
            class="nav-item nav-link {% if request.user.username in request.path %}active{% endif %}">
            Profile
         </a>
          <a href="{% url 'users:log_out' %}" class="nav-item nav-link">Log out</a>
        </div>
        {% else %}
        <div class="navbar-nav ml-auto">
          <a href="{% url 'users:log_in' %}"
            class="nav-item nav-link {% if request.path == '/users/login/' %}active{% endif %}">Log in</a>
          <a href="{% url 'users:signup' %}"
            class="nav-item nav-link {% if request.path == '/users/signup/' %}active{% endif %}">Sign up</a>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  <!-- ... removed for brevity -->
</body>
</html>